= NETUNUS - Pool Safer
Nina Holzinger, Konstantin Frank, David Andraschko
1.0
:sourcedir: ../src/main/java
:icons: font
:toc: left

== Projektstatus 10. Mai 2020

=== Zusammenfassung

Wir haben daran gearbeitet das Projekt vollständig am RPI laufen zu lassen und
mit Hilfe einer Angular-App einen Alarm darzustellen.

=== Ziel

Das Ziel für diese Woche (KW 19) war unser Projekt nun ohne Probleme auf
dem Raspberry Pi 4 laufen lassen zu können. Als nächsten Schritt wollten
wir einen Alarm auf einer Website (blinkender Hintergrund) anzeigen lassen.

=== Ergebnisse

Das Projekt läuft nun vollständig auf dem Raspberry Pi 4. Das inkludiert eine
MariaDB, einen MQTT-Server, einen Quarkus-Server und einen NGINX-Webserver.

Um den Quarkus-Server auf dem Raspberry Pi laufen lassen zu können, haben wir
ein Docker-Image unseres Quarkus-Projektes erstellen müssen.

TIP: *Warum?*
Dieser Schritt ist notwendig um das Backend im Docker-Compose verwenden zu können.

*Docker-Compose Datei dafür:*

----
version: "3"

services:
  db:
    image: mariadb:10.3.22-bionic
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: pool-notifier
      MYSQL_USER: pool-notifier
      MYSQL_PASSWORD: secret
    volumes:
      - ./mariadb:/var/lib/mysql

  mosquitto:
    image: eclipse-mosquitto:1.6.9
    ports:
      - 1883:1883


//// Aktuell nicht im Docker-Compose enthalten
  backend:
    image: andraschkodocker/backend-netunus-jvm:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      MP_MESSAGING_INCOMING_POOL_HOST: mosquitto
      QUARKUS_DATASOURCE_URL: jdbc:mariadb://db:3306/pool-notifier
    depends_on:
      - db
      - mosquitto
////


  frontend:
    image: nginx:1.18.0
    ports:
      - 80:80
    volumes:
      - ./src:/usr/share/nginx/html
----

NOTE: Aktuell muss der Quarkus-Server manuell vom RPI aus gestartet werden um
Komplikationen zu vermeiden.

Das Image vom Quarkus-Backend ist aktuell für einen AMD-Prozessor ausgerichtet und
muss für einen ARM-Prozessor erstellt werden.

Wir haben auch schon mit der Angular App bekommen und uns damit beschäftigt
wie wir die Sensordaten vom Quarkus-Server holen können.
Dabei ist jedoch ein Problem aufgetreten.

=== Probleme

*Wir bekommen folgende Fehlermeldung:*

IMPORTANT: Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://192.168.0.129:8080/pool. (Reason: CORS request did not succeed)

Die Lösung dafür lernten wir eigentlich schon im Fach Sew, jedoch
funktioniert diese aus für uns unschlüssigen Gründen nicht.
Um dieses Problem schnellstmöglich zu beheben haben wir schon Prof. Aistleitner
um Hilfe gebeten.