= NETUNUS - Pool Safer
Nina Holzinger, Konstantin Frank, David Andraschko
1.0
:sourcedir: ../src/main/java
:icons: font
:toc: left

== Abstract

Die Anzahl an Pools in privaten Haushalten steigt immer mehr.
Vielleicht haben ja auch Sie einen Pool zu Hause.
Dabei gibt es leider nur ein großes Problem, und zwar die Beaufsichtigung von Kleinkindern
und Haustieren. Es ist praktisch unmöglich die ganze Zeit aufzupassen,
dadurch entstehen leider immer häufiger Badeunfälle.

Um dies zu verhindern entwicklen wir ein System,
welches Badeunfälle verhindern soll. Fällt ein Kind oder ein Tier in den Pool,
dann löst unser System einen akustischen und visuellen Alarm aus.
Damit soll sichergestellt werden, dass möglichst schnell geholfen werden kann.

== Projektvideos
=== Kurzfassung

*Was ist Netunus? Wofür wird es verwendet?*

video::p5PX3PFFbJc[youtube, width="800px", height="400px"]

=== Extended Version

*Technische Umsetzung, Anwendungsfälle, Projektteam, ...*

video::2SgHfNun2m4[youtube, width="800px", height="400px"]

== Neugierig geworden

include::https://konstantinfrank01.github.io/safer-pool-docs/inhaltsverzeichnis.html[Wirf einen Blick in unsere Doku]

