= NETUNUS - Minutes of Meeting
Author: David Andraschko, Konstantin Frank
:sourcedir: ../src/main/java
:icons: font
:toc: left
:imagesdir: ../asciidocs/images/

.Teilnehmer
|===
|anwesend |Verteiler

|Konstantin Frank
|

|David Andraschko
|

|Nina Holzinger
|

|Prof. T. Stütz
|

|Prof. R. Reder
|
|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|Discord

|von-bis
|25.05.2020 - ITP-Einheiten
|Dauer
|in etwa 20-30 Minuten
|===

== Besprochene Themen

* GUI
* Film
* Docker/Logging

== Vereinbarungen/Empfehlungen

=== GUI

Wir sollten eigenen Buttons für 15 Minuten/30 Minuten/45 Minuten statt dem Eingabefeld erstellen.
Der Status (Icon) soll gelb sein, wenn die Aufsichtsperson schwimmen ist.
Statt dem Wort "Überwachung" wäre es besser, wenn wir "Schutz" schreiben.
Der Countdown solls schön groß und gut ersichtlich sein.

=== Film

Wir sollen einen Film für das Projekt erstellen.

https://youtu.be/01mW_kXN6ko

=== Docker/Logging

Es wäre super, wenn wir einen MiniClient erstellen, der alle MQTT-Messages mitloggt. z.B. mittels RollingLog
(z.B. 3 Files mit je 10kB, nach dem 3. File löscht sich das erste und ein neues leeres wird erstellt).

Die verschiedenen Komponenten unseres Projektes (MQTT-Server, DB, ...) sollen in eigenen Docker-Containern laufen.

